// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('c:/My_Startups_2024/TheShopScanner/ShopScannerUniversal/node_modules/react');
var { Component } = React;
var ReactNative = require('c:/My_Startups_2024/TheShopScanner/ShopScannerUniversal/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('ShopScannerUniversal', appParameters);
});
require('c:/My_Startups_2024/TheShopScanner/ShopScannerUniversal/index.android.js');